spring.application.name=insurance-manager-api

#Configuration H2
spring.datasource.url=jdbc:h2:file:./insurance;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

#Disable default database initialization
spring.sql.init.mode=never

#JSON ISO 8601 dates
spring.jackson.serialization.write-dates-as-timestamps=false